name: Deploy Branch and Run Tests

on:
  repository_dispatch:
    types: [deploy-and-test]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B (suite de tests)
        uses: actions/checkout@v3

      - name: Extract Branch Name
        id: extract_branch_name
        run: echo "branch=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV

      - name: Generate Amplify URL
        run: echo "AMPLIFY_URL=https://${{ secrets.AMPLIFY_DOMAIN }}/${branch}" >> $GITHUB_ENV

      - name: Ensure Branch Exists in Amplify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          set -e
          BRANCH_NAME="$branch"
          if aws amplify list-branches --app-id "${{ secrets.AMPLIFY_APP_ID }}" --region "${{ secrets.AWS_REGION }}" | grep -q "\"branchName\": \"$BRANCH_NAME\""; then
            echo "Branch $BRANCH_NAME already exists."
          else
            echo "Creating branch $BRANCH_NAME in Amplify."
            aws amplify create-branch --app-id "${{ secrets.AMPLIFY_APP_ID }}" --branch-name "$BRANCH_NAME" --region "${{ secrets.AWS_REGION }}"
          fi

      - name: Trigger Amplify Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: echo "Amplify will deploy branch $branch"

      - name: Wait for Deployment to Complete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          set -e
          BRANCH_NAME="$branch"
          MAX_RETRIES=20
          RETRIES=0
          while true; do
            JOB_ID=$(aws amplify list-jobs --app-id "${{ secrets.AMPLIFY_APP_ID }}" --branch-name "$BRANCH_NAME" --query 'jobSummaries[0].jobId' --output text --region "${{ secrets.AWS_REGION }}")
            STATUS=$(aws amplify get-job --app-id "${{ secrets.AMPLIFY_APP_ID }}" --branch-name "$BRANCH_NAME" --job-id "$JOB_ID" --query 'job.summary.status' --output text --region "${{ secrets.AWS_REGION }}")
            echo "Current status: $STATUS"
            if [[ "$STATUS" == "SUCCEED" ]]; then
              echo "Deployment succeeded!"
              break
            elif [[ "$STATUS" == "FAILED" ]]; then
              echo "Deployment failed!"
              exit 1
            fi
            if [[ $RETRIES -ge $MAX_RETRIES ]]; then
              echo "Timeout waiting for deployment to complete."
              exit 1
            fi
            ((RETRIES++))
            sleep 15
          done

      - name: Run Tests
        run: |
          echo "Running tests against deployed URL: $AMPLIFY_URL"
          cd path/to/tests
          npm ci
          npm run test:e2e -- --baseUrl=$AMPLIFY_URL
